import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Gallery.module.css'

const Gallery: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			
			<main className={styles.main}>
				<div className={styles.header}>
					<h1 className={styles.title}>
						Sara Ranus
					</h1>
					<div className={styles.header_image}>
						<Image src="/stock/spray.png" alt="Vercel Logo" width={480} height={240} />
					</div>
				</div>
				<span className={styles.logo_container}>
					<Image className={styles.logo} src="/logo.jpg" alt="Vercel Logo" width={128} height={128} />
				</span>
				<div className={styles.gallery}>
					{
						["cats.jpg", "church.jpg", "dreary.jpg", "fall.jpg", "fireflies.jpg", "full_moon.jpg", "lake.jpg", "lined_stream.jpg", "love_shrooms.jpg", "overgrowth.jpg", "red_sun.jpg", "snow.jpg", "snowy_clearing.jpg"]
							.map((file) => <div className={styles.gallery_item} key={file}>
								<Image src={"/gallery/" + file} layout="fill" objectFit="contain"></Image>
							</div>)
					}
				</div>
			</main>
			
			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	)
}

export default Gallery
